image: hpclib/hiepacs

Find:
  artifacts:
    name: find_ctests
    expire_in: 1 week
    paths:
     - modules/find/tests/build/Testing/
  script:
    - cd modules/find/tests
    - mkdir -p build
    - cd build
    - cmake .. -DENABLE_CTEST=ON -DQUARK_COMPONENTS="HWLOC"
    - ctest -V
